name: Keep Render Service Awake

on:
  schedule:
    # 台灣時間 (UTC+8) 08:00 - 20:00，每 10 分鐘執行一次
    - cron: "*/10 0-12 * * *"
  workflow_dispatch:  # 允許手動觸發

jobs:
  keep-awake:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render API
        run: curl -s https://declaration-wi4s.onrender.com/api/health > /dev/null
